** Context
   Switzerland tourism website [url] is a collection of the best things to visit in Switzerland. The goal of this project is to provide a
   chat UI that enables a user to query the swizerland tourism webiste in Natural language. The website also provides a map to visualize the
   locations of the tourism spots to visit.

** Try it here
   [url of the website]

** How does it work?
   The LLM used to process the natural language of the user is Mistral (specify model). By looking at an user's prompt Mistral is able to call the swiss tourism api with relevant parameter. This is a demonstration of Mistral's function calling capabilities [url of function calling]
   Example of a workflow:
   User Prompt:
   "What are some mountains is switzerland that I could visit?"
   Swiss Tourism API:
   Mistral will attempt to call the api using the correct parameters.
   
   The https request to the api looks like this:
   https://opendata.myswitzerland.io/v1/destinations?facet.filter=placetypes%3A<parameter>

   <parameter> has to be a word that the api recognizes.
   In this example we expect mistral to pick the word "mountains" as a parameter.
   
   API response:
   The api gives back a list of destinations that match the parameter. In our case a list of mountains with their coordinates. We can use this information to enhance
   mistrals response to the user as well as populate the map.
   
  ** Run it locally
   1. clone this repo git clone [url of repo]
   2. create a new python virtual environment
   3. pip install the requirements
   4. start the web server fastapi main.py

  Tailwind is used for CSS of the website. To make your own changes you will need to use the tailwind cli to create an output.css.

  
      

      
      
      
